steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: '# Message with markdown.\n Thank you for submitting your first issue! We welcome contributions in this repository.'
    pr-message: 'Message that will be displayed on users' first pr. Look, a `code block` for markdown.'